services:
  - type: web
    name: eksplosa
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: strapi-database
          property: connectionString

databases:
  - name: strapi-database
    plan: free
