services:
  - type: web
    name: eksplosa-be
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~20.16.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: .tmp/strapi.db
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
